name = "integrations"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[daemon.scheduler]
task_timeout_min = 1
task_repo_type = "disk"

[runners."local:docker"]
enabled = true
run_timeout_min = 1

[[testcases]]
name = "issue-1349-silent-failure"
instances = { min = 1, max = 1, default = 1 }

[[testcases]]
name = "issue-1432-task-timeout"
instances = { min = 1, max = 1, default = 1 }